/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
plugins {
//    val springBootVersion = "2.2.0.RELEASE"
//    id("org.springframework.boot") version springBootVersion
//    id("io.spring.dependency-management") version "1.0.8.RELEASE"
    id("java")
    id("io.freefair.lombok") version "5.3.0"
    application
}

version = "1.0.0-SNAPSHOT"

application {
    mainClassName = "q8_1.Application"
}

dependencies {
//    implementation("com.graphql-java:graphql-java:14.0") // NEW
//    implementation("com.graphql-java:graphql-java-spring-boot-starter-webmvc:1.0") // NEW
//    implementation("com.google.guava:guava:26.0-jre") // NEW
//    implementation("org.springframework.boot:spring-boot-starter-web")
//    testImplementation("org.springframework.boot:spring-boot-starter-test")
    implementation("com.google.guava:guava:30.0-jre")
    compileOnly("org.projectlombok:lombok:1.18.16")
    annotationProcessor("org.projectlombok:lombok:1.18.16")
    testCompileOnly("org.projectlombok:lombok:1.18.16")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.16")
}

repositories {
    jcenter()
    mavenCentral()
}